modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="warcoloniesextension"
version="1.0.0"
displayName="War Colonies Extension"
authors="Alessandra YppyLê"
description='''
Extensão de estratégia, guerra, logística e simulação
para complementar o MineColonies com sistemas avançados
de diplomacia, economia, construção virtual e invasões.
'''

[[dependencies.warcoloniesextension]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.warcoloniesextension]]
modId="neoforge"
mandatory=true
versionRange="[21.1.216,)"
ordering="NONE"
side="BOTH"

[[dependencies.warcoloniesextension]]
modId="minecolonies"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
