modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId = "warcolonies"
version = "0.1.0"
displayName = "War Colonies"
updateJSONURL = ""

[[dependencies.warcolonies]]
    modId="minecolonies"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
